vich_uploader:
    db_driver: orm
    
    metadata:
      type: attribute
      
    mappings:
       formation_video:
         uri_prefix: /video/formation
         upload_destination: '%kernel.project_dir%/public/video/formation'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
